### ISSUE TITLE
Nested arrays with objects fail to be merged

### ISSUE THREAD

**Issue by mauritslamers** [marcello3d/trimerge#2]
When trying to merge a JS object structure containing nested arrays which contain objects, the merge will always fail.

The main reason for this is that the uniqueness operation in https://github.com/marcello3d/json-diff3/blob/master/src/json-diff3.ts#L35 will simply try to convert the object in a string. As this results in `[Object object]` any additional object will complain about having duplicate keys in the array.

**Comment by mauritslamers** [comment]
To add to the issue above: I understand that the solution is not easy. The purpose of this function is to return something which identifies the element across all versions of the object given. There is no definite way in which an object in an array can be identified without specifying some kind of primary key to it as part of the data structure. The order of the elements might be changed which does not always have to be significant. Arrays are used as sets, and have to be in JSON as it doesn't support sets. 
Nevertheless, as a workaround I made the order in the array significant by providing a `getArrayItemKey` function which returns the index. This solves the error above, but might cause issues when the order changes. 

```
const result = diff3(a, b, c, {
  getArrayItemKey: function (item, index, arrayPath) {
    return index;
  }
});
```

**Comment by marcello3d** [comment]
Yea, this definitely needs more documentation. The intention is that there is no one right answer, and it's data-structure specific how you want to handle array elements, hence the getArrayItemKey option.

In the latest version of the library (now called trimerge), this is even more customizable.

That said, all this is still very much experimental so don't use it unless you're ok with the API changing a lot.
