### ISSUE TITLE
Question: Does it assume that the first version (s1) is the "base"?

### ISSUE THREAD

**Issue by AdamCoulterOz** [marcello3d/trimerge#26]
Does it follow this kind of workflow?

1. Compare S2 to S1 -> S2delta
2. Compare S3 to S1 -> S3delta
3. Compare S2delta to S3delta for conflicts
4. Merge S2delta and S3delta

If so, it would be good to make it more explicit to offer a function where it is `merge(base, left, right)` to be more compliant with how 3-way merge is designed to work.

https://www.drdobbs.com/tools/three-way-merging-a-look-under-the-hood/240164902

**Comment by marcello3d** [comment]
> Does it assume that the first version (s1) is the "base"?
Yes, and in fact in the function definitions I call them `orig`, `left`, and `right`.

> Does it follow this kind of workflow?
That's a reasonable way of thinking about it, and for string diff it works like this. For Array/Object/Map diffing, I look at all three at the same time.

**Comment by AdamCoulterOz** [comment]
Would it make sense to resolve Array/Object/Map diffing back to being strings at their component levels? i.e. matching attributes and fields, then performing a baseful string merge?

**Comment by marcello3d** [comment]
I’m not sure what problem you’re trying to solve with that, could you give me more context?
